sudo: false

language: node_js

node_js:
  - node

install:
  - npm ci

script:
  - npm run build
  - npm run 
  - npm run preview

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  on:
    branch: main